name: Upload to GCR
on: 
  push: 
    branches: 
      - main
  create:
      tags:
        - v*
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.AUTH_PROVIDER  }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
          create_credentials_file: true
      - name: Read Google Credentials file
        id: get-token
        run: echo "::set-output name=credentials::$(cat ${{ steps.auth.outputs.credentials_file_path }})"
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ steps.get-token.outputs.credentials }} # can be base64 encoded or plain text
          registry: gcr.io
          project_id: ${{ steps.auth.outputs.project_id }}
          image_name: backend
          image_tag: latest,v1
          dockerfile: ./Dockerfile
          context: ./