name: Upload to GCR
on: 
  push: 
    branches: 
      - main
  create:
      tags:
        - v*
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '${{ secrets.AUTH_PROVIDER  }}'
          service_account: '${{ secrets.SERVICE_ACCOUNT }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Google Container Registry (GCR) GCloud SDK
        run: gcloud auth configure-docker
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gcr.io/${{ steps.auth.outputs.project_id }}/death-causes:${{ github.sha }}, gcr.io/${{ steps.auth.outputs.project_id }}/death-causes:latest


         